# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41ea755736f070c0426f2c9a3e14e0e3bfbdb65a8e67767356dc82f00ef85089889ab7f996242e398970af9a6964367aaa13471d69752142df11a9237ccb16c2

test:
  secret_key_base: e4ae00827c1a2c70c7bba792325e6a6bc2aeac4e98684bbac385e5b2142e93e472918db938155111c13b7cb744baa821c32a12bdf5405228d3ab9d2e568b60ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
